### ISSUE TITLE
[상품관리] 상품삭제하기

### ISSUE THREAD

**Issue by soing22** [zhakul/hello-shop#33]

**Comment by wonjong85** [comment]
체크박스 선택 후 선택삭제를 눌렀을 때,
"선택한 자료를 정말 삭제하시겠습니까?"라는 문구가 나오도록 해야 하는데 잘 모르겠습니다.
도와주세요.

**Comment by wonjong85** [comment]
승현이의 조언으로 도움받았습니다.
